{{- if .Values.sandbox.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "agentpane.sandbox.namespace" . }}
  labels:
    {{- include "agentpane.labels" . | nindent 4 }}
    agentpane.io/managed: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
{{- end }}
